openapi: 3.0.3
info:
  title: CMS API
  version: 0.1.0

paths:
  /hello/{name}:
    get:
      tags:
        - Default
      summary: Greet a user
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Greeting
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
